---
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include Debian variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Identify host cpu architecture
  shell: dpkg --print-architecture
  register: __debian_cpu_arch
  changed_when: false

- name: Set cpu architecture fact
  set_fact:
    debian_cpu_arch: "{{ __debian_cpu_arch.stdout }}"

- name: Update package cache
  apt:
    update_cache: "True"
  changed_when: false

- name: Install prereq packages
  package:
    name: "{{ __debian_prereqs }}"
    state: present
  when: __debian_prereqs is defined

- name: Install docker repo signing key
  apt_key:
    url: "{{ docker_download_root }}/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Install docker repo and update cache
  apt_repository:
    repo: "deb [arch={{ debian_cpu_arch }}] {{ docker_download_root }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_channel }}"
    state: present
    update_cache: true
...
