---
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build Test
'on':
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'meta/**'
      - 'README.md'
      - 'LICENSE'
      - '.github/**'
      - '.gitignore'
      - '.yamllint'
  schedule:
    - cron: '0 0 * * 0'

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu1804
          - ubuntu2004
          - debian9
          - debian10
          - centos7
          - centos8
          - fedora32
          - fedora33

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install molecule[docker] yamllint ansible-lint==5.0.10 ansible==2.9.18

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          TEST_DISTRO: ${{ matrix.distro }}
